### ISSUE TITLE
Getting `defaultSelected` instead of `selected` in HTML

### ISSUE THREAD

**Issue by hovancik** [cferdinandi/reef#90]
Hi,

I have a weird issue, where I am not able to use `defaultXXX`, ie `defaultSelected`.

I am using Reef 7.6.6 in Electron app and I am not doing anything fancy: 

```
                            <select name="type">
                              <option ${reminder.type === 'repeat' ? 'defaultSelected' : ''}>repeat</option>
                              <option ${reminder.type === 'once' ? 'defaultSelected' : ''}>once</option>
                              <option ${reminder.type === 'cron' ? 'defaultSelected' : ''}>cron</option>
                            </select>
```
I tried to reproduce in codepen, but everything works fine there. 

I noticed, though, that in codepen the resulting value in html is `selected`, while in my project I am getting `defaultselected`.

```
<option defaultselected="">once</option>
<option selected="">once</option>
```
Not really sure where to look, I must be doing some rookie mistake.

**Comment by hovancik** [comment]
@cferdinandi  I was able to find the bug: https://codepen.io/hovancik/pen/YzpPRQw?editors=1111

When you render the select with first render, `default` works fine. Issue is when you render, then change some value which will cause select to be rendered: default will not work. 

You can see if you set `editing` to `false` and then click on edit. When `editing` is `true` on first render, all works fine.

**Comment by cferdinandi** [comment]
Ohhh ok, I see what's happening here. So, currently, `default*` values only show up on the very first render of the app. But that doesn't account for the fact the element itself is rendering for the first time in this case, even though the app itself rendered already.

This is definitely a bug. I'll see what I can do.

**Comment by cferdinandi** [comment]
Oh, and thanks for the reduced test case. Super helpful!

**Comment by cferdinandi** [comment]
I just released Reef v8.x, which now uses a `[reef-default-selected]` attribute for a bit more control and accuracy. You can learn more about that here: http://localhost:1313/advanced/#default-and-state-based-html-attributes

**Comment by hovancik** [comment]
Thanks! I'll try it out. 

Btw found a small issues in your [codepen](https://codepen.io/cferdinandi/pen/jOVPgdo), here's a working version

```
var app = new Reef('#app', {
	data: {
		agreeToTOS: true
	},
	template: function (props) {
		return `
			<label>
				<input type="checkbox" reef-checked="${props.agreeToTOS}">
			</label>
      
      <label for="wizards">Who is the best wizard?</label>
			<select>
				<option>Harry</option>
				<option reef-default-selected>Hermione</option>
				<option>Neville</option>
			</select>`;
	}
});

setTimeout(function () {
  app.data.agreeToTOS = false;
}, 3000);

app.render()
```

**Comment by hovancik** [comment]
It doesn't seems to work, though? In the codepen, first option is selected

**Comment by cferdinandi** [comment]
Oops, caught a small bug in my `isFalsy()` check. 

Should be fixed with v8.0.2. Thanks y'all!

**Comment by hovancik** [comment]
Hi @cferdinandi , your example now work, but I am still having issues with getting my code to work. 

I've updated my code to latest changes in reef: https://codepen.io/hovancik/pen/YzpPRQw

Would you mind taking a look? I am not sure what I am doing wrong.

**Comment by cferdinandi** [comment]
Hmm... that is REALLY odd. Reopening this one.

**Comment by cferdinandi** [comment]
Got it. Your Pen was using a cached version of Reef v7.x. Looks like the CDN hasn't flushed "latest major" yet. 

I'm using an explicit version number here and its working as expected: https://codepen.io/cferdinandi/pen/OJbygby

**Comment by hovancik** [comment]
Hi @cferdinandi , would you mind looking again? https://codepen.io/hovancik/pen/YzpPRQw

I still had issues on my project, so I created a bit more complicated example, where it doesn't work. Not sure what's wrong, but I got a feeling I am doing something wrong on "philosophical/language" level

"Edit" changes the state and turns on/off the edit form. If you click it, it seems not work correctly. First load is OK. I added 2 forms on page to show that. 

Thanks a bunch!

**Comment by cferdinandi** [comment]
Hey, again, your demo is loading an older version of Reef (probably due to some CDN caching stuff.

I'm going to update the docs to stress this more clearly, but you should use this pattern for the CDN hosted file:

```html
<script src="https://cdn.jsdelivr.net/npm/reefjs@8/dist/reef.min.js"></script>
```

For some reason, omitting the `@8` is loading version 7.x at the moment.

**Comment by cferdinandi** [comment]
See here: https://codepen.io/cferdinandi/pen/oNYbgeb

**Comment by cferdinandi** [comment]
I also noticed that the Reduced Test Case CodePen wasn't using the recommend pattern. I just fixed that.

**Comment by hovancik** [comment]
Well, I am trying from Incognito in Chrome (https://codepen.io/cferdinandi/pen/oNYbgeb), but still I don't think I see what I think I should see. 

![image](https://user-images.githubusercontent.com/4745859/106913470-4e880800-6704-11eb-8afe-7224d09ac7f1.png)

I click on second "Edit"

![image](https://user-images.githubusercontent.com/4745859/106913545-652e5f00-6704-11eb-8a67-95c1300e4175.png)

And the same "Edit"

![image](https://user-images.githubusercontent.com/4745859/106913648-8000d380-6704-11eb-90db-d6bc060295e2.png)

I should see the same things as in first picture, right? Or I am not understanding this correctly? 

Same when I click first Edit, I would expect default values to be there 

![image](https://user-images.githubusercontent.com/4745859/106913836-b76f8000-6704-11eb-8ec8-598aecf0a0bf.png)

I am seeing the same in my app, where I am using `npm` and `<script src="node_modules/reefjs/dist/reef.js"></script>` with 8.0.2

**Comment by cferdinandi** [comment]
Hmm, this may be an issue with Reef's currently approach to diffing. The `reef-*` attributes shouldn't be showing up in the UI at all though. 

Good catch!

**Comment by cferdinandi** [comment]
Alright, this should be resolved with v8.0.3.
